### ISSUE TITLE
No composer?

### ISSUE THREAD

**Issue by stephanvierkant** [Monetbil/monetbil-php#1]
This package doesn't use a package manager like composer. Adding a composer.json file will help developers to use this packages in a framework like Symfony. Why isn't there a composer.json file here?

**Comment by ntongserges** [comment]
We simplified it the most.
You can give us one if you wish.
In the meantime we will do it

Thank you

**Comment by muarachmann** [comment]
Can I work on the composer installation of this? and also for it to support frameworks like laravel?
